### ISSUE TITLE
Debug module is required, but not set in dependencies

### ISSUE THREAD

**Issue by Devoter** [Cloud-Automation/node-modbus#208]
jsmodbus version 3.0.0:
`Error: Cannot find module 'debug'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/.../node_modules/jsmodbus/src/modbus-client.js:1:75)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)`

**Comment by stefanpoeter** [comment]
It is now, see branch v3.1.0-dev. Thanks for your help.
