### ISSUE TITLE
Cannot install v3.1.6 (on Windows -- due to serialport@4.0.7)

### ISSUE THREAD

**Issue by jacobq** [Cloud-Automation/node-modbus#263]
Just tried to use this in an empty / dummy to try it out, but I encountered build errors during `npm install`.

<details>
<summary>npm install output</summary>

```
C:\Users\jacob\Documents\tmp\modbus-dummy-server>npm install jsmodbus

> serialport@4.0.7 install C:\Users\jacob\Documents\tmp\node_modules\serialport
> node-pre-gyp install --fallback-to-build

node-pre-gyp info it worked if it ends with ok
node-pre-gyp verb cli [
node-pre-gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
node-pre-gyp verb cli   'C:\\Users\\jacob\\Documents\\tmp\\node_modules\\serialport\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp',
node-pre-gyp verb cli   'install',
node-pre-gyp verb cli   '--fallback-to-build'
node-pre-gyp verb cli ]
node-pre-gyp info using node-pre-gyp@0.6.32
node-pre-gyp info using node@12.16.3 | win32 | x64
node-pre-gyp verb command install []
node-pre-gyp info check checked for "C:\Users\jacob\Documents\tmp\node_modules\serialport\build\Release\serialport.node" (not found)
node-pre-gyp http GET https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7/serialport-v4.0.7-node-v72-win32-x64.tar.gz
node-pre-gyp http 404 https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7/serialport-v4.0.7-node-v72-win32-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7/serialport-v4.0.7-node-v72-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for serialport@4.0.7 and node@12.16.3 (node-v72 ABI) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7/serialport-v4.0.7-node-v72-win32-x64.tar.gz
node-pre-gyp verb command build [ 'rebuild' ]
node-pre-gyp ERR! Tried to download(undefined): https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7/serialport-v4.0.7-node-v72-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for serialport@4.0.7 and node@12.16.3 (node-v72 ABI) (falling back to source compile with node-gyp)
node-pre-gyp http Connection closed while downloading tarball file
node-pre-gyp verb command build [ 'rebuild' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.CppBuild.targets(321,5): er
ror MSB3491: Could not write lines to file "Release\obj\serialport\serialport.tlog\serialport.lastbuildstate". The process ca
nnot access the file 'C:\Users\jacob\Documents\tmp\node_modules\serialport\build\Release\obj\serialport\serialport.tlog\seria
lport.lastbuildstate' because it is being used by another process. [C:\Users\jacob\Documents\tmp\node_modules\serialport\buil
d\serialport.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\jacob\AppData\Roaming\nvm\v12.16.3\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\jacob\\AppData\\Roaming\\nvm\\v12.16.3\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Users\\jacob\\Documents\\tmp\\node_modules\\serialport\\build\\Release\\serialport.node" "--module_name=serialport" "--module_path=C:\\Users\\jacob\\Documents\\tmp\\node_modules\\serialport\\build\\Release"
gyp ERR! cwd C:\Users\jacob\Documents\tmp\node_modules\serialport
gyp ERR! node -v v12.16.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\jacob\AppData\Roaming\nvm\v12.16.3\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\jacob\Documents\tmp\node_modules\serialport\build\Release\serialport.node --module_name=serialport --module_path=C:\Users\jacob\Documents\tmp\node_modules\serialport\build\Release' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\jacob\Documents\tmp\node_modules\serialport\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Windows_NT 10.0.18363
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\jacob\\Documents\\tmp\\node_modules\\serialport\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\jacob\Documents\tmp\node_modules\serialport
node-pre-gyp ERR! node -v v12.16.3
node-pre-gyp ERR! node-pre-gyp -v v0.6.32
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\jacob\AppData\Roaming\nvm\v12.16.3\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\jacob\Documents\tmp\node_modules\serialport\build\Release\serialport.node --module_name=serialport --module_path=C:\Users\jacob\Documents\tmp\node_modules\serialport\build\Release' (1)
npm WARN rollback Rolling back strip-ansi@3.0.1 failed (this is probably harmless): EPERM: operation not permitted, scandir 'C:\Users\jacob\Documents\tmp\node_modules\serialport\node_modules\node-pre-gyp\node_modules\request\node_modules\har-validator\node_modules\chalk\node_modules'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\jacob\Documents\tmp\package.json'
npm WARN tmp No description
npm WARN tmp No repository field.
npm WARN tmp No README data
npm WARN tmp No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! serialport@4.0.7 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the serialport@4.0.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jacob\AppData\Roaming\npm-cache\_logs\2020-05-13T19_09_09_105Z-debug.log
```

</details>

[2020-05-13T19_09_09_105Z-debug.log](https://github.com/Cloud-Automation/node-modbus/files/4624151/2020-05-13T19_09_09_105Z-debug.log)

FWIW, I also tried in an elevated command prompt (running as Administrator) and got the same results. I have build tools installed (and have been building/running current versions of `serialport` while developing an electron app on this same machine).

**Comment by jacobq** [comment]
Ug, this seems to be a side-effect of something else (parent package.json somerwhere? npm? Windows?). I can install with `npm install -g jsmodbus` and with `yarn`.
